server:
  port: 8080
  portTLS: 8888
  certFile: config/testcert.cert
  keyFile: config/testcert.key
  apiOnly: False
  source: gcvit
  binSize: 500000

users:
   user1: password1
   user2: password2
   user3: password3

b73v5:
  location: assets/B73v5.NAM-illumina_reduced.vcf.gz
  name: B73 v5 and NAMs
  format: vcf
